<a href="https://colab.research.google.com/github/mirnayt/Automatizaci-n-de-Operaciones-del-Agregador/blob/main/notebook/Limpiar_transacciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El presente archivo tiene como objetivo, poder manipuar los datos de las transacciones para poder limpiar el archivo. El archivo contiene muchas columnas que no son funcionales en el análisis de datos, asi como columnas con tipo de dato incorrecto, etc.

In [ ]:
#Importar librerías que se usaran en la limpieza
import pandas as pd
import os
import zipfile

In [ ]:
#Revisar en que carpeta estan cargados los archivos para poder leerlo
os.getcwd()

'/content'

In [ ]:
# Se lee y guarda la infromación en la variable en un dataframe abreviado "df"
df = pd.read_excel("/content/BD_TRANSACCIONES_PRUEBA.xlsx")

In [ ]:
#Se convierte el archivo de xlsx a formato csv
df.to_csv('archivo.csv', index=False)

In [ ]:
#Se revisa el tipo de dato de cada columna
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 60 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ID                                   200 non-null    object
 1   TIPO DE TX                           200 non-null    object
 2   MERCHANT                             200 non-null    int64
 3   USER ID                              200 non-null    object
 4   BIN                                  200 non-null    int64
 5   TIPO BIN                             200 non-null    int64
 6   PAN TERMINACION                      200 non-null    int64
 7   CLAVE DE OPERACION                   200 non-null    int64
 8   MODO DE ENTRADA                      200 non-null    int64
 9    IMPORTE                             200 non-null    float64
 10  MONEDA                               96 non-null     object
 11  FECHA DE APLICACION                  200 non-null    datetime64[ns]
 12  AFILIACION                           92 non-null     object
 13  CLAVE VENTA                          98 non-null     object
 14  NOMBRE TARJETAHABIENTE               90 non-null     object
 15  PROPINA                              92 non-null     object
 16  BANCO ADQUIRIENTE                    106 non-null    object
 17  NOMBRE DE COMERCIO                   98 non-null     object
 18  APROBADA                             95 non-null     object
 19  CLAVE DE RECHAZO                     120 non-null    object
 20  DESCRIPCION DE RECHAZO               91 non-null     object
 21  PRODUCTO                             104 non-null    object
 22  BANCO EMISOR                         101 non-null    object
 23  MARCA                                101 non-null    object
 24  AUTORIZACION                         103 non-null    object
 25  LONGITUD                             200 non-null    float64
 26  LATITUD                              200 non-null    float64
 27  NOMBRE                               104 non-null    object
 28  APELLIDO                             109 non-null    object
 29  EMAIL                                94 non-null     object
 30  PAGO REFERENCIADO                    99 non-null     object
 31  CADENA                               104 non-null    object
 32  REFERENCIA                           104 non-null    object
 33  IMPORTE NETO                         200 non-null    float64
 34  TASA                                 97 non-null     object
 35  IVA TASA                             107 non-null    object
 36  TASA BANCARIA                        109 non-null    object
 37  IVA TASA BANCARIA                    94 non-null     object
 38  TASA COMISIONISTA                    200 non-null    float64
 39  IVA TASA COMISIONISTA                200 non-null    float64
 40  UTILIDAD A REPARTIR                  98 non-null     object
 41  IMPORTE POR OPERACION                200 non-null    float64
 42  IVA DE IMPORTE POR OPERACION         200 non-null    float64
 43  RETENCION POR CONTRACARGO            105 non-null    object
 44  GARANTIA LIQUIDA                     86 non-null     object
 45  MANEJO ADMINISTRATIVO                93 non-null     object
 46  IVA POR MANEJO ADMINISTRATIVO        96 non-null     object
 47  NUMERO DE PAGOS                      99 non-null     object
 48  TASA DE MESES SIN INTERESES          200 non-null    object
 49  IVA POR TASA DE MESES SIN INTERESES  200 non-null    object
 50  TOTAL DE INGRESOS FEENICIA           92 non-null     object
 51  TOTAL DE INGRESOS BANCO              107 non-null    object
 52  MONTO TOTAL DE COMISION              200 non-null    float64
 53  MONTO TOTAL A DISPERSAR              200 non-null    float64
 54  CODIGO                               101 non-null    object
 55  FECHA DE DISPERSION                  200 non-null    datetime64[ns]
 56  CUSTOMER INFO                        98 non-null     object
 57  OPERATIVA                            200 non-null    object
 58  MES                                  200 non-null    object
 59  AÑO                                  200 non-null    int64
dtypes: datetime64[ns](2), float64(10), int64(7), object(41)
memory usage: 93.9+ KB

In [ ]:
#Muestra Totas las columnas de la tabla
df.columns

Index(['ID', 'TIPO DE TX', 'MERCHANT', 'USER ID', 'BIN', 'TIPO BIN',
       'PAN TERMINACION', 'CLAVE DE OPERACION', 'MODO DE ENTRADA', ' IMPORTE ',
       'MONEDA', 'FECHA DE APLICACION', 'AFILIACION', 'CLAVE VENTA',
       'NOMBRE TARJETAHABIENTE', 'PROPINA', 'BANCO ADQUIRIENTE',
       'NOMBRE DE COMERCIO', 'APROBADA', 'CLAVE DE RECHAZO',
       'DESCRIPCION DE RECHAZO', 'PRODUCTO', 'BANCO EMISOR', 'MARCA',
       'AUTORIZACION', 'LONGITUD', 'LATITUD', 'NOMBRE', 'APELLIDO', 'EMAIL',
       'PAGO REFERENCIADO', 'CADENA', 'REFERENCIA', 'IMPORTE NETO', 'TASA',
       'IVA TASA', 'TASA BANCARIA', 'IVA TASA BANCARIA', 'TASA COMISIONISTA',
       'IVA TASA COMISIONISTA', 'UTILIDAD A REPARTIR', 'IMPORTE POR OPERACION',
       'IVA DE IMPORTE POR OPERACION', 'RETENCION POR CONTRACARGO',
       'GARANTIA LIQUIDA', 'MANEJO ADMINISTRATIVO',
       'IVA POR MANEJO ADMINISTRATIVO', 'NUMERO DE PAGOS',
       'TASA DE MESES SIN INTERESES', 'IVA POR TASA DE MESES SIN INTERESES',
       'TOTAL DE INGRESOS FEENICIA', 'TOTAL DE INGRESOS BANCO',
       'MONTO TOTAL DE COMISION', 'MONTO TOTAL A DISPERSAR', 'CODIGO',
       'FECHA DE DISPERSION', 'CUSTOMER INFO', 'OPERATIVA', 'MES', 'AÑO'],
      dtype='object')

In [ ]:
#Muestra de 5 datos de la tabla completa para ver como se visualiza el dato
df.head(5)

,ID,TIPO DE TX,MERCHANT,USER ID,BIN,TIPO BIN,PAN TERMINACION,CLAVE DE OPERACION,MODO DE ENTRADA,IMPORTE,...,TOTAL DE INGRESOS FEENICIA,TOTAL DE INGRESOS BANCO,MONTO TOTAL DE COMISION,MONTO TOTAL A DISPERSAR,CODIGO,FECHA DE DISPERSION,CUSTOMER INFO,OPERATIVA,MES,AÑO
0,TX100000,SALE,58219,Usuario 39,539177,601100,8303,55882581,2,1960.10,...,NaN,-,44.16,842.96,NaN,2023-05-05,NaN,EN LINEA,MAYO,2024
1,TX100001,SALE,56341,Usuario 26,601100,601100,1639,56862416,5,1145.79,...,DatoPrueba,NaN,6.31,682.70,-,2023-04-21,NaN,EN LINEA,MAYO,2024
2,TX100002,SALE,59362,Usuario 15,557910,557910,6798,58693186,5,895.66,...,NaN,NaN,7.79,1317.13,DatoPrueba,2023-02-14,NaN,EN LINEA,MAYO,2024
3,TX100003,DEVOLUCION,56315,Usuario 25,458909,539177,9063,57803462,2,1466.87,...,NaN,NaN,36.22,1412.97,NaN,2023-12-12,DatoPrueba,TRADICIONAL,MAYO,2024
4,TX100004,CANCEL,57692,Usuario 33,539177,557910,1977,58630067,2,764.17,...,-,NaN,29.86,1077.51,NaN,2023-12-09,NaN,TRADICIONAL,FEBRERO,2023

In [ ]:
#modifica la columna de fecha de aplicación para que se reconozca como una columna de fecha
df['FECHA DE APLICACION']= pd.to_datetime(df['FECHA DE APLICACION'], errors="raise")

In [ ]:
#Se eligen las columnas que van a quedarse en el df
columnas_seleccionadas = ['ID','TIPO DE TX','MERCHANT','USER ID','TIPO BIN',' IMPORTE ','FECHA DE APLICACION','NOMBRE TARJETAHABIENTE','BANCO EMISOR', 'MARCA', 'APROBADA','LONGITUD', 'LATITUD','IMPORTE NETO','OPERATIVA','MES','AÑO']

#el nuevo df, se le atribuye a la variable "df"
df = df[columnas_seleccionadas]

In [ ]:
#Muestra el # de columnas y filas del DF

df.shape

(200, 17)

In [ ]:
#Revisas como queda la info
df.head(5)

,ID,TIPO DE TX,MERCHANT,USER ID,TIPO BIN,IMPORTE,FECHA DE APLICACION,NOMBRE TARJETAHABIENTE,BANCO EMISOR,MARCA,APROBADA,LONGITUD,LATITUD,IMPORTE NETO,OPERATIVA,MES,AÑO
0,TX100000,SALE,58219,Usuario 39,601100,1960.10,2023-11-10,NaN,NaN,DatoPrueba,NaN,-109.943002,16.507449,975.49,EN LINEA,MAYO,2024
1,TX100001,SALE,56341,Usuario 26,601100,1145.79,2023-07-21,DatoPrueba,-,NaN,NaN,-97.826547,27.359567,1845.23,EN LINEA,MAYO,2024
2,TX100002,SALE,59362,Usuario 15,557910,895.66,2023-02-13,NaN,NaN,NaN,NaN,-92.589143,24.342773,131.95,EN LINEA,MAYO,2024
3,TX100003,DEVOLUCION,56315,Usuario 25,539177,1466.87,2023-08-06,NaN,NaN,NaN,-,-115.703417,24.313142,1227.45,TRADICIONAL,MAYO,2024
4,TX100004,CANCEL,57692,Usuario 33,557910,764.17,2023-05-05,NaN,DatoPrueba,-,NaN,-88.057415,15.221296,1605.66,TRADICIONAL,FEBRERO,2023

In [ ]:
#como renombrar un encabezado o columna
#df_columnas_selecionadas.rename(columns = {"TESORERIA TPV": "TIPO DE OPERATIVA"}, inplace=True)

In [ ]:
#df_columnas_selecionadas.groupby('USER ID').agg({'IMPORTE':'sum'}).sort_values('IMPORTE',ascending=False).head(10)

In [ ]:
#Se descarga el archivo en formato csv para poder leerlo en power bi
df.to_csv("Transacciones_limpias.csv")